language: python
branches:
  except:
  - documentation
matrix:
  fast_finish: true
env:
  matrix:
  - PACKER_VERSION="0.7.1" AWS_INSTANCE_TYPE="t2.medium" AWS_VIRTUALIZATION_TYPE="hvm"
    AWS_SOURCE_AMI="ami-0070c468" IP_INDEX=15 STRIP_COMMENTS=true
  - PACKER_VERSION="0.7.1" AWS_INSTANCE_TYPE="t2.medium" AWS_VIRTUALIZATION_TYPE="hvm"
    AWS_SOURCE_AMI="ami-0070c468" IP_INDEX=15 STRIP_COMMENTS=false
  - PACKER_VERSION="0.7.1" AWS_INSTANCE_TYPE="m3.medium" AWS_VIRTUALIZATION_TYPE="pv"
    AWS_SOURCE_AMI="ami-0870c460" IP_INDEX=16 STRIP_COMMENTS=true
  global:
  - secure: h3RZYIa758G++1qj5GIprArX+sOSSF5ZRaW6kxX0GtIAg2VZ5wGAVRza7HOb8fDbCeOcKmC6irJeQzMP6gQ/ileYdUeYzB+RZjk3frMvl0Wo6Q1OcCdPWcd7bdYfHGT8+/amFPv5TslU3afoAk+HNObowyRoN6IHdvkTe3wxnWo=
  - secure: oS1WF0V2iWkrk22fjV/s538qcNmSLBDi0+ZK61dL3DtmZsUGiyBcRSZjRIlzHr9m6tXRfO8JsqURKnfc7l/Fuhk/QrMBoGfFmQIK3DpmV+LGtu87oIki6RXPsxYX4BcA0g2bW1SKtIrWzRLnc9bjsG9PcAKzsG+QseQugoFYVqg=
  - secure: js9SACVxzqJPJZL9cJe7gXBt59OrczwgLcRPyxnonCp5Rv8XIzyJ2wwC4+DnxV3OhLVOlN2xOsN+hL0etVQMEyCNESPrMIbVEfaY9c+np6ZAAvztZZO3ZsjE/vRfE5UcPwT8dLv9vqV9G9jXeooAtrpQO1H9pfg7wDCuGfsNdHQ=
  - secure: t7yW36zVVaMSyvPZ4EGfn0qLmEdMzT48XDJXzE+pMZdZwn1U/A7ztRdd+YUM707gLpYOCH1Q6XVUlvtzzFjwGBD9eaCmY4eonrj07nfrB+aWTozUGAVEPAc5ddHzkg+xwuv2Asn1YFzOmWSVk0iSoK/5nYIBivbrkT7weqbAh5Q=
  - secure: z38F9r0k0CxiitJPz5CBBf3Vbqq2Q7fYhzErOvuKANUgV+8G9nbkMQaTjDaaDxIbHVN/U1AjFhozDcmplpv7Fh+hv94EhQCXZFO5scYr3Z6so49KRCp+llnEUm5BApVjRpYlnoEqxOw9bmhoo3kQ6yXkhetWvbfHc38/NaIUZRQ=
  - secure: LErjTN/ZQjVl5jQq280ALBvLofw+YLId9iXkyDt45nOkK6inaXTODofcuESSeH1SF9b0IvuLeC9kC33r8eqwUgc+SE9X9VHfLRxyKbhVIl0XUrg7dBQXGdls66ChewihW+NCiLIytORNuZzV+iBehqYYiG6xXDw+ITsoWq/y6e8=
  - secure: mIx2EFW3INRUgVR4DFW2TnOcz95OohRsuIhfdsg/icjTb1ou92lu7aeJchWXbJXLSudTsvflhJCIXAgWI2NSRG3OWzsg/JHXl6xOUEzDw+wgqDSjYi+iQyALKtSgdPRFfn4CIuxz8FaLpZyy9+ZtQsk6+kmV28w+D9QbB3qb8s4=
  - AWS_REGION="us-east-1"
  - DEFAULT_SSH_USER="ubuntu"
  - PACKER_GRAPHITE_BUILD_NAME="travis-packer"
  - PACKER_GRAPHITE_EMAIL="thetrashcan@gmail.com"
before_install:
- sudo apt-get update -y --fix-missing
install:
- curl -o /tmp/packer.zip -L "https://dl.bintray.com/mitchellh/packer/packer_${PACKER_VERSION}_linux_amd64.zip"
- sudo unzip -d /usr/local/bin /tmp/packer.zip
before_script:
- mkdir ~/.aws
- printf "[default]\naws_access_key_id = ${AWS_ACCESS_KEY}\naws_secret_access_key
  = ${AWS_SECRET_KEY}\noutput = text\nregion = ${AWS_REGION}\n" | tee -a ~/.aws/config
  >/dev/null
- chmod 600 ~/.aws/config
- cp example-vars.json vars.json
script:
- "./build.sh amazon-ebs"
- if grep -q 'Builds finished but no artifacts were created' packer.log; then test
  ! true; fi
- echo `awk '{ print $NF }' packer.log | tail -n 1 | tr -d '\n'` | tee ec2.ami
- echo `aws ec2 run-instances --image-id $(cat ec2.ami) --security-groups "${AWS_SECURITY_GROUP}"
  --key-name "${AWS_KEYPAIR_NAME}" --instance-type "${AWS_INSTANCE_TYPE}" --placement
  "AvailabilityZone=${AWS_REGION}a" | grep INSTANCES | cut -f 8` | tee ec2.instance
- echo `wget -q -O - http://lisforge.net/ip.php` > travis.ip
- aws ec2 authorize-security-group-ingress --group-id $AWS_SECURITY_GROUP_ID --protocol
  tcp --port 2003 --cidr $(cat travis.ip)/32
- test-scripts/run-tests.sh "`cat ec2.ip`"
after_script: 
notifications:
  slack:
    secure: Y3nLfeeulseAOx94Q84QHKsV5wuhqAw2vcfkSS18mnQ2rEJKrO+V/OROGGgJgv+7DFLLFvfDpqgb0wJSoHkI+opAnlqXV9HkXg9fir8Q+M2k2hCl/cl/j0fTJBnNHDr35FuCSteBkVRjGFINw9Ligq2XxAUvxAAouTjbmfEGqDEqs3k+KZN8Xl/SduqWmkhI2hvLcWG3mUdnyWMMI2ivDfk6lYUvFXOcDHHkbxxRv/c0Ass3WtDzAjDM4dI0plDUoQxXtTBuqVplnxvA+5X2znideE4cWzAEcChtPtp0VLIrICGaF/7uaYvf0crf17r8vjZlZ4OchmP7JulwQ2den8Mwluq8NDeBUYj4+cWmnA9+3UwCEu1vLJTCfj0Wv6qA54T/COHb1E2jXx2tnGOerIPZ22jULBuksK0kxY4NUbKWVOiOT2hKFhHCF59wGe55l6ryqx7Kb6Ucg39Rea/TU96WPdHg+jUIWjhc0G7a7x8EAMTVew/CKsHOCpOc9Lz8bxLWoepusjel3iVdgQ0EuySpHYeOVM91JJpnFh/CEkPZssBARU5bTd59/ZPad6bfBGAbd5yPHvoSCG91eavHVp7l4T6VcVE8N4E4iGh5CJ8sw8y/6hMjKi3wRU6nBK0nCvHI5m0fNWIB/aNwWahuuIYgM8c3RAzfKYlYLKZUtfs=
dd:
- openssl aes-256-cbc -K $encrypted_94a4c510d0d1_key -iv $encrypted_94a4c510d0d1_iv
  -in deploy_key.enc -out deploy_key -d
